// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneClickHost.Api.Data;

#nullable disable

namespace OneClickHost.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614161722_AddProjectEvents")]
    partial class AddProjectEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneClickHost.Api.Models.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildLogs")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageTag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LockedByNodeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status", "NextRunAt", "CreatedAt");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.DeploymentAiDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId")
                        .IsUnique();

                    b.ToTable("DeploymentAiDiagnoses");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.DeploymentDiagnosticSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetectedStack")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FailureStep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RelevantLogExcerpt")
                        .HasColumnType("text");

                    b.Property<string>("RepositoryTree")
                        .HasColumnType("jsonb");

                    b.Property<string>("SelectedFiles")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId")
                        .IsUnique();

                    b.ToTable("DeploymentDiagnosticSnapshots");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ExecutionNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentBuilds")
                        .HasColumnType("integer");

                    b.Property<string>("LabelsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrentBuilds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PublicOrPrivateBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExecutionNodes");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ComposeDeleteVolumesOnDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("ComposeEnvJson")
                        .HasColumnType("text");

                    b.Property<string>("ComposeFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ComposeLiveUrlsJson")
                        .HasColumnType("text");

                    b.Property<string>("ComposePostStartCommands")
                        .HasColumnType("text");

                    b.Property<string>("ComposeProjectName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ComposeRoutesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subfolder")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ProjectDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildLogs")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComposeProjectName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicUrlsJson")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LockedByNodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "NextRunAt", "CreatedAt");

                    b.ToTable("ProjectDeployments");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ProjectEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExecutionNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RouteTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("ExecutionNodeId");

                    b.HasIndex("RouteTargetId");

                    b.HasIndex("Type");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ProjectEvents");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.RouteTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutionNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ProjectDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionNodeId");

                    b.HasIndex("Host");

                    b.HasIndex("ProjectDeploymentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("RouteTargets");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedStack")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExposureProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NetworkAliases")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subfolder")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Deployment", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.ExecutionNode", "LockedByNode")
                        .WithMany("Deployments")
                        .HasForeignKey("LockedByNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneClickHost.Api.Models.Service", "Service")
                        .WithMany("Deployments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LockedByNode");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.DeploymentAiDiagnosis", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.Deployment", "Deployment")
                        .WithOne("AiDiagnosis")
                        .HasForeignKey("OneClickHost.Api.Models.DeploymentAiDiagnosis", "DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.DeploymentDiagnosticSnapshot", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.Deployment", "Deployment")
                        .WithOne("DiagnosticSnapshot")
                        .HasForeignKey("OneClickHost.Api.Models.DeploymentDiagnosticSnapshot", "DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.EnvironmentVariable", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.Service", "Service")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Project", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ProjectDeployment", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.ExecutionNode", "LockedByNode")
                        .WithMany("ProjectDeployments")
                        .HasForeignKey("LockedByNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneClickHost.Api.Models.Project", "Project")
                        .WithMany("ProjectDeployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LockedByNode");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ProjectEvent", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.ProjectDeployment", "Deployment")
                        .WithMany("Events")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneClickHost.Api.Models.ExecutionNode", "ExecutionNode")
                        .WithMany("Events")
                        .HasForeignKey("ExecutionNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneClickHost.Api.Models.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClickHost.Api.Models.RouteTarget", "RouteTarget")
                        .WithMany("Events")
                        .HasForeignKey("RouteTargetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deployment");

                    b.Navigation("ExecutionNode");

                    b.Navigation("Project");

                    b.Navigation("RouteTarget");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.RouteTarget", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.ExecutionNode", "ExecutionNode")
                        .WithMany("RouteTargets")
                        .HasForeignKey("ExecutionNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneClickHost.Api.Models.ProjectDeployment", "ProjectDeployment")
                        .WithMany("RouteTargets")
                        .HasForeignKey("ProjectDeploymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneClickHost.Api.Models.Project", "Project")
                        .WithMany("RouteTargets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClickHost.Api.Models.Service", "Service")
                        .WithMany("RouteTargets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExecutionNode");

                    b.Navigation("Project");

                    b.Navigation("ProjectDeployment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Service", b =>
                {
                    b.HasOne("OneClickHost.Api.Models.Project", "Project")
                        .WithMany("Services")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Deployment", b =>
                {
                    b.Navigation("AiDiagnosis");

                    b.Navigation("DiagnosticSnapshot");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ExecutionNode", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Events");

                    b.Navigation("ProjectDeployments");

                    b.Navigation("RouteTargets");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Project", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ProjectDeployments");

                    b.Navigation("RouteTargets");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.ProjectDeployment", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("RouteTargets");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.RouteTarget", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.Service", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("EnvironmentVariables");

                    b.Navigation("RouteTargets");
                });

            modelBuilder.Entity("OneClickHost.Api.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
