#!/usr/bin/env bash
set -euo pipefail

output_file="${1:-.generated/multinode-secrets.env}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

rand_b64() {
  openssl rand -base64 "$1" | tr -d '\n'
}

require_cmd openssl
mkdir -p "$(dirname "$output_file")"

cat >"$output_file" <<EOF
# Generated by scripts/generate-execution-secrets.sh
# Keep this file private. Do not commit it.
JWT_SECRET=$(rand_b64 48)
COMPOSESHIP_SECRET_KEY=$(rand_b64 32)
INVITE_CODE_PEPPER=$(rand_b64 32)
EXECUTION_NODE_REGISTRATION_TOKEN=$(rand_b64 32)
EXECUTION_NODE_TOKEN=$(rand_b64 32)
POSTGRES_PASSWORD=$(rand_b64 24)
EOF

chmod 600 "$output_file" 2>/dev/null || true

echo "Wrote secrets to $output_file"
echo "Load them with:"
echo "  set -a; source $output_file; set +a"
